services:
  postgres:
    image: "postgres:15-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  pgbouncer:
    image: "bitnami/pgbouncer:1.24.0"
    restart: always
    ports:
      - "6432:6432"
    environment:
      POSTGRESQL_HOST: "postgres"
      POSTGRESQL_USERNAME: "postgres"
      POSTGRESQL_PASSWORD: "postgres"
      PGBOUNCER_AUTH_TYPE: "trust"
      PGBOUNCER_IGNORE_STARTUP_PARAMETERS: "extra_float_digits"
    depends_on:
      - postgres

  pgbouncer_exporter:
    build:
      context: .
    restart: always
    ports:
      - "9127:9127"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@pgbouncer:6432/pgbouncer?sslmode=disable"
      DEFAULT_LABELS: "instance=pg1 env=dev"
    depends_on:
      - pgbouncer
